/* Full Plate menu: courses and services. Shared by the homepage and the Kitchen Check page. */
const COURSES=[
  {id:"found",name:"Foundations",emoji:"🧱",line:"Customers find you the moment they go looking.",color:"#B8996A"},
  {id:"cx",name:"Customer Experience",emoji:"🤝",line:"Every lead followed up. Every customer comes back.",color:"#1B2F33"},
  {id:"owner",name:"Owner Experience",emoji:"😊",line:"Get your time back. See everything at a glance.",color:"#6FA3C2"},
  {id:"growth",name:"Growth",emoji:"🚀",line:"The kitchen is ready. Now let's fill every seat!",color:"#531211"}
];
const S=[
  {id:"web",course:"found",main:1,name:"Website + Lead Capture",line:"A site that turns visitors into calls and bookings.",steps:["We map what customers need to find in the first few seconds.","We build a fast, mobile-first site with clear ways to reach you.","Every form and call lands in one place so nothing gets lost."],vis:{t:"browser"}},
  {id:"gbp",course:"found",main:1,name:"Google Business Profile",line:"Show up right when locals and visitors search.",steps:["We claim, clean up and verify your listing.","Photos, hours, services and categories, done right.","Regular posts and updates keep you active in Maps."],vis:{t:"map"}},
  {id:"crm",course:"found",main:1,name:"Organized Customer Database",line:"Every customer in one place, not five.",steps:["We pull contacts out of inboxes, POS systems and spreadsheets.","We clean, tag and organize them.","Your team gets one simple place to look anyone up."],vis:{t:"contacts",rows:[["JM","Regular"],["AK","New"],["RS","VIP"],["TB","Lapsed"]]}},
  {id:"brand",course:"found",main:1,name:"Brand Guidelines",line:"Look like the same business everywhere.",steps:["We gather what you already have.","We set your colors, fonts, logo rules and tone.","You get one guide anyone on your team can follow."],vis:{t:"swatch",quote:"Friendly. Local. Straight to the point."}},
  {id:"app",course:"found",name:"Mobile App",line:"Your business on their home screen.",steps:["We figure out if an app is worth it for you. Often it isn't.","If it is, we design it around repeat visits.","Launch, push messages and updates handled."],vis:{t:"phone",msgs:[["in","Your order is ready for pickup. See you soon!"],["out","On my way"]]}},
  {id:"ai",course:"found",name:"AI Consulting",line:"Know where AI actually helps your business.",steps:["We look at where your week goes.","We point out the tasks AI can safely take on.","We set it up and show your team how to use it."],vis:{t:"chat",title:"Kitchen notes",msgs:[["in","Where does most of your week go?"],["out","Answering the same questions over and over."],["in","That's a great fit for AI. Let's start there."]]}},
  {id:"desk",course:"cx",main:1,name:"24/7 Front Desk",line:"Your business answers, even when you can't.",steps:["We learn your FAQs, hours and booking rules.","An assistant answers chats and texts day and night.","Anything it can't handle comes straight to you."],vis:{t:"chat",title:"Your Business, online now",msgs:[["out","Are you open Sunday night?"],["in","We sure are, 11 to 9. Want me to save you a table?"],["out","Yes, 4 people at 7"]],typing:true}},
  {id:"reviews",course:"cx",main:1,name:"More Reviews",line:"Happy customers, asked at the right moment.",steps:["We find the best moment to ask, right after a great visit.","A friendly text goes out automatically.","You see new reviews and replies in one place."],vis:{t:"stars"}},
  {id:"missed",course:"cx",main:1,name:"Missed-Call Text-Back",line:"Missed a call? They get a text right away.",steps:["When a call is missed, a text goes out automatically.","The customer can reply, book or ask a question.","The conversation lands in your inbox, ready to pick up."],vis:{t:"phone",msgs:[["in","Sorry we missed your call! How can we help? Reply here and we'll get right back to you."],["out","Any openings Friday?"]]}},
  {id:"comms",course:"cx",name:"Customer Communications",line:"The right message to the right person, on time.",steps:["Reminders, confirmations and thank-yous, set up once.","Texts and emails written in your voice.","It runs on its own. You approve the words."],vis:{t:"phone",msgs:[["in","Reminder: your appointment is tomorrow at 2:00. Reply C to confirm."],["out","C"],["in","You're all set. See you then!"]]}},
  {id:"upsell",course:"cx",main:1,name:"Upsells + Return Visits",line:"Bring customers back before they forget you.",steps:["We find who hasn't been back in a while.","We send them a timely reason to return.","You see who came back and which message did it."],vis:{t:"phone",msgs:[["in","It's been six months! Time for your next visit. Want us to save you a spot?"],["out","Yes please, Thursday?"]]}},
  {id:"referral",course:"cx",name:"Referral Systems",line:"Turn your best customers into your best marketing.",steps:["We pick a simple, fair reward.","Customers get an easy way to share you.","Every referral is tracked and thanked."],vis:{t:"phone",msgs:[["in","Thanks for sending a friend our way! Your next visit is on us."],["out","Amazing, thank you!"]]}},
  {id:"auto",course:"owner",main:1,name:"Business Automations",line:"The busywork, handled without you.",steps:["We list the tasks you repeat every week.","We connect your tools so they hand off on their own.","You get hours back, every week."],vis:{t:"flow",steps:["New lead comes in","Welcome text goes out","Added to your calendar"]}},
  {id:"aissistant",course:"owner",main:1,name:"AIssistant",line:"An assistant that knows your business.",steps:["We teach it your services, policies and voice.","It drafts replies, posts and to-dos for you.","You review and send. It learns as you go."],vis:{t:"chat",title:"AIssistant",msgs:[["out","Draft a reply to this morning's review."],["in","Done. Want it warmer or shorter?"],["out","Warmer"]],typing:true}},
  {id:"kpi",course:"owner",main:1,name:"KPI Dashboards",line:"See everything at a glance.",steps:["We pick the handful of numbers that matter.","We pull them from the tools you already use.","One screen, updated on its own."],vis:{t:"chart",label:"New leads this week",value:"38",delta:"+12%",bars:[40,55,48,62,58,75,88]}},
  {id:"reporting",course:"owner",name:"Automated Reporting",line:"A plain-English report in your inbox.",steps:["We decide what you want to know each week.","Reports build and send themselves.","Written so you can read it in two minutes."],vis:{t:"doc",kicker:"Weekly report",title:"Your week in two minutes"}},
  {id:"voice",course:"owner",name:"Brand Kit + Voice",line:"Sound like you, every time.",steps:["We capture how you talk to customers.","We turn it into a voice guide and templates.","Your team and your AI tools use the same voice."],vis:{t:"swatch",quote:"Warm, local, never pushy."}},
  {id:"aios",course:"owner",main:1,name:"AI Operating System",line:"AI tools working together across your business.",steps:["We map how work moves through your business.","We connect AI tools to each step.","You run the business. The system runs the routine."],vis:{t:"flow",steps:["Question answered by AI","Booking created","Follow-up scheduled"]}},
  {id:"ads",course:"growth",main:1,name:"Google, Social + AI Search Ads",line:"Show up where your next customer is looking.",steps:["We pick the channels that fit your season and goals.","We write, launch and manage the campaigns.","You see exactly what each campaign brought in."],vis:{t:"ad",text:"Now booking for the season.",btn:"Book now"}},
  {id:"seo",course:"growth",main:1,name:"SEO + GEO",line:"Get found on Google and in AI answers.",steps:["We see where you show up today.","We fix pages, listings and content.","We track rankings and AI mentions over time."],vis:{t:"search",q:"best breakfast near me"}},
  {id:"social",course:"growth",main:1,name:"Social Media Growth",line:"Posts that bring people in, not just likes.",steps:["We plan content around your busy seasons.","We create and schedule the posts.","We track what turns into real customers."],vis:{t:"social"}},
  {id:"partners",course:"growth",name:"Sponsorships + Partnerships",line:"Get in front of the right local crowd.",steps:["We find local events and businesses that share your customers.","We set up the partnership and the follow-up.","Every new contact goes into your database."],vis:{t:"contacts",rows:[["SV","Sponsor"],["LB","Partner"],["EV","Event"],["NC","New lead"]]}},
  {id:"blogs",course:"growth",name:"Blogs + Content",line:"Answer customers' questions before they ask.",steps:["We find what your customers search for.","We write helpful articles in your voice.","Each one keeps working for months."],vis:{t:"doc",kicker:"New article",title:"5 things to know before you visit",img:true}},
  {id:"cro",course:"growth",main:1,name:"Conversion Rate Optimization",line:"More calls from the same traffic.",steps:["We watch where visitors drop off.","We test clearer pages and buttons.","Keep what works, drop what doesn't."],vis:{t:"chart",label:"Visitors who call or book",value:"6.2%",delta:"+1.8 pts",bars:[30,34,33,41,45,52,60]}}
];
